services:
  api-gateway:
    build: ./gateway-express
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      - "schedule-back"
      - "schedule-google-modules"
      - "schedule-parser"
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-api-gateway
    environment:
      - PORT=${API_GATEWAY_PORT}
      # BACKEND
      - API_GATEWAY_BACKEND_ROUTE=/api
      - API_GATEWAY_BACKEND_PROTOCOL=${API_GATEWAY_BACKEND_PROTOCOL}
      - API_GATEWAY_BACKEND_TARGET=schedule-back:${SCHEDULE_BACKEND_PORT}/api
      - API_GATEWAY_BACKEND_TARGET_SOCKETS=schedule-back:${SCHEDULE_BACKEND_PORT}/socket.io
      # PARSER
      - API_GATEWAY_PARSER_ROUTE=/parser
      - API_GATEWAY_PARSER_PROTOCOL=${API_GATEWAY_PARSER_PROTOCOL}
      - API_GATEWAY_PARSER_TARGET=schedule-parser:${SCHEDULE_PARSER_PORT}/parser
      # GOOGLE MODULES
      - API_GATEWAY_GOOGLE_MODULES_ROUTE=/google-modules
      - API_GATEWAY_GOOGLE_MODULES_PROTOCOL=${API_GATEWAY_GOOGLE_MODULES_PROTOCOL}
      - API_GATEWAY_GOOGLE_MODULES_TARGET=schedule-google-modules:${SCHEDULE_GOOGLE_MODULES_PORT}/google-modules

  schedule-front:
    build: ./schedule_mitit_front
    ports:
      - ${SCHEDULE_FRONT_PORT}:${SCHEDULE_FRONT_PORT}
    depends_on:
      - "schedule-back"
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-frontend

  schedule-back:
    build: ./schedule-backend
    depends_on:
      - "mongodb"
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-backend
    environment:
      - PORT=${SCHEDULE_BACKEND_PORT}
      - MONGO_URL=${SCHEDULE_MONGO_URL}
      - MONGO_DB_NAME=${SCHEDULE_MONGO_DB_NAME}

  schedule-parser:
    build: ./schedule-parser
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-parser
    environment:
      - PORT=${SCHEDULE_PARSER_PORT}
      - MONGO_URL=${SCHEDULE_MONGO_URL}
      - MONGO_DB_NAME=${SCHEDULE_MONGO_DB_NAME}

  schedule-google-modules:
    build: ./schedule.google-modules
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-google-modules
    environment:
      - PORT=${SCHEDULE_GOOGLE_MODULES_PORT}
      - MONGO_URL=${SCHEDULE_MONGO_URL}
      - MONGO_DB_NAME=${SCHEDULE_MONGO_DB_NAME}

  mongodb:
    image: mongo:4.4.6
    ports:
      - ${SCHEDULE_MONGODB_PORT}:27017
    volumes:
      - schedule_mongodb_data:/data/db
    command: mongod --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SCHEDULE_MONGODB_INIT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SCHEDULE_MONGODB_INIT_PASSWORD}
    labels:
      promtail.logs: enable
      application_name: main/mongodb

volumes:
  schedule_mongodb_data:

networks:
  schedule:
    name: schedule
