version: "3"

services:
  schedule-front:
    build: ./schedule_mitit_front
    ports:
      - ${SCHEDULE_FRONT_PORT}:${SCHEDULE_FRONT_PORT}
    expose:
      - ${SCHEDULE_FRONT_PORT}
    depends_on:
      - 'schedule-back'
    restart: always
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    environment:
      - SSL_CRT_FILE=/etc/nginx/ssl/schedule.mitit.crt
      - SSL_KEY_FILE=/etc/nginx/ssl/schedule.mitit.key

  schedule-back:
    build: ./schedule-backend
    ports:
      - ${SCHEDULE_BACKEND_PORT}:${SCHEDULE_BACKEND_PORT}
    expose:
      - ${SCHEDULE_BACKEND_PORT}
    restart: always
    volumes:
      - /etc/nginx/ssl/:/schedule/ssl/

  schedule-parser:
    build: ./schedule-parser
    ports:
      - ${SCHEDULE_PARSER_PORT}:${SCHEDULE_PARSER_PORT}
    expose:
      - ${SCHEDULE_PARSER_PORT}
    restart: always
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/

  schedule-google-modules:
    build: ./schedule.google-modules
    ports:
      - ${SCHEDULE_GOOGLE_MODULES_PORT}:${SCHEDULE_GOOGLE_MODULES_PORT}
    expose:
      - ${SCHEDULE_GOOGLE_MODULES_PORT}
    restart: always
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --auth
    restart: always

volumes:
 schedule_mongodb_data:
   external: true 
