services:
  schedule-front:
    build: ./schedule_mitit_front
    ports:
      - ${SCHEDULE_FRONT_PORT}:${SCHEDULE_FRONT_PORT}
    expose:
      - ${SCHEDULE_FRONT_PORT}
    depends_on:
      - "schedule-back"
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-frontend

  schedule-back:
    build: ./schedule-backend
    ports:
      - ${SCHEDULE_BACKEND_PORT}:${SCHEDULE_BACKEND_PORT}
    expose:
      - ${SCHEDULE_BACKEND_PORT}
    depends_on:
      - "mongodb"
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-backend

  schedule-parser:
    build: ./schedule-parser
    ports:
      - ${SCHEDULE_PARSER_PORT}:${SCHEDULE_PARSER_PORT}
    expose:
      - ${SCHEDULE_PARSER_PORT}
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-parser

  schedule-google-modules:
    build: ./schedule.google-modules
    ports:
      - ${SCHEDULE_GOOGLE_MODULES_PORT}:${SCHEDULE_GOOGLE_MODULES_PORT}
    expose:
      - ${SCHEDULE_GOOGLE_MODULES_PORT}
    restart: always
    volumes:
      - ${SSL_PATH_ON_OS}:${SSL_PATH_IN_CONTAINER}
    labels:
      promtail.logs: enable
      application_name: main/schedule-google-modules

  mongodb:
    image: mongo:4.4.6
    ports:
      - ${SCHEDULE_MONGODB_PORT}:27017
    volumes:
      - schedule_mongodb_data:/data/db
    command: mongod --auth
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SCHEDULE_MONGODB_INIT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SCHEDULE_MONGODB_INIT_PASSWORD}
    labels:
      promtail.logs: enable
      application_name: main/mongodb

volumes:
  schedule_mongodb_data:

networks:
  schedule:
    name: schedule
