apiVersion: 1

contactPoints:
  - orgId: 1
    name: discord
    receivers:
      - uid: ddh4mt21adcshe
        type: discord
        settings:
          url: https://discord.com/api/webhooks/1222837277495918622/umut_lufTHfKq1qNaOn_44yVNQvqcYH2o524-RHmeuotm8QEn6k0VHErPaOTp-DBDn0r
          use_discord_username: false
        disableResolveMessage: false

policies:
  - orgId: 1
    receiver: grafana-default-email
    group_by:
      - grafana_folder
      - alertname
    routes:
      - receiver: discord
        object_matchers:
          - - prob_fail
            - =
            - "true"
        group_interval: 2m
        repeat_interval: 5m

groups:
  - orgId: 1
    name: DevOps
    folder: alerting
    interval: 30s
    rules:
      - uid: bdh4mmmqpua68a
        title: Services probes
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              datasource:
                type: prometheus
                uid: PBFA97CFB590B2093
              editorMode: code
              expr: probe_success
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 1
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 30s
        annotations:
          description: ""
          runbook_url: ""
          summary: ""
        labels:
          "": ""
          prob_fail: "true"
        isPaused: false
