services:
  grafana:
    image: grafana/grafana:10.4.1
    ports:
      - "3000:3000"
    networks:
      - schedule
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    labels:
      promtail.logs: enable
      application_name: main/grafana

  loki:
    image: grafana/loki:2.8.11
    ports:
      - "3100:3100"
    networks:
      - schedule
    volumes:
      - loki_data:/loki
    labels:
      promtail.logs: enable
      application_name: main/loki

  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    networks:
      - schedule
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/:/etc/prometheus/
    labels:
      promtail.logs: enable
      application_name: main/prometheus

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.24.0
    ports:
      - "9115:9115"
    networks:
      - schedule
    volumes:
      - ./blackbox/blackbox.yaml:/config/blackbox.yml
    command: "--config.file=/config/blackbox.yml"
    labels:
      promtail.logs: enable
      application_name: main/blackbox-exporter

networks:
  schedule:
    name: schedule

volumes:
  grafana_data:
  loki_data:
  prometheus_data:
  blackbox-exporter_data:
