###################################################################################
# HERE ARE DEFINED ALL TARGETS THAT SHOULD BE MONITORED BY THE BLACKBOX EXPORTERS #
# THE STRUCTURE OF THIS TEMPLATE IS DESCRIBED IN THE LINE BELOW                   #
# <BLACKBOX_EXPORTER_IP_PORT>:_:<<MODULE>:_:<LOCATION>:_:<GEOHASH>:_:<TARGET_URL> #
###################################################################################
- targets:
    # Main machine Blackbox exporter
    - blackbox-exporter:9115:_:http_2xx:_::_::_:http://prometheus:9090/
    - blackbox-exporter:9115:_:http_2xx:_::_::_:http://loki:3100/ready
    - blackbox-exporter:9115:_:http_2xx:_::_::_:http://node-exporter:9100/
