global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "blackbox"
    metrics_path: /probe
    file_sd_configs:
      - files:
          - /etc/prometheus/blackbox-targets.yml
    relabel_configs:
      # adds "module" label in the final labelset
      - source_labels: [__address__]
        regex: ".*:_:(.*):_:.*:_:.*:_:.*"
        target_label: module
      # adds "geohash" label in the final labelset
      - source_labels: [__address__]
        regex: ".*:_:.*:_:.*:_:(.*):_:.*"
        target_label: geohash
      # rewrites "instance" label with corresponding URL
      - source_labels: [__address__]
        regex: ".*:_:.*:_:.*:_:.*:_:(.*)"
        target_label: instance
      # rewrites "job" label with corresponding location name
      - source_labels: [__address__]
        regex: ".*:_:.*:_:(.*):_:.*:_:.*"
        target_label: job
      # passes "module" parameter to Blackbox exporter
      - source_labels: [module]
        target_label: __param_module
      # passes "target" parameter to Blackbox exporter
      - source_labels: [instance]
        target_label: __param_target
      # the Blackbox exporter's real hostname:port
      - source_labels: [__address__]
        regex: "(.*):_:.*:_:.*:_:.*:_:.*"
        target_label: __address__
