{
 "title": "Nginx",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total request",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request per minute",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 19, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "increase(nginx_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}